Fix issue10, fix lint warnings
lean-delivery/ansible-role-gitlab pull request #11
Opened 2018-12-17 15:58 UTC by ViachaslauKabak

gitlab template was fixed
lint warnings were fixed

2018-12-17 18:14 UTC, tgadiev requested changes
Please, see discussions

2018-12-17 18:14 UTC, tgadiev commented on .travis.yml
> +  - pip install --upgrade ansible==2.5.* molecule==2.17 ansible-lint docker-py pyOpenSSL PyYAML pytest==3.7.4
Please, remove ansible-lint installation from this line. It's installed on next step.

2018-12-17 18:14 UTC, tgadiev commented on tasks/install.yml
>    loop:
Comment for line 11 & 15:
Please, always use the map syntax, regardless of how many pairs exist in the map. Like this:
```yaml
 - name: "Check if GitLab is already installed."
   stat:
     path: /usr/bin/gitlab-ctl
   register: gitlab_file
```

2018-12-17 18:14 UTC, tgadiev commented on tasks/install.yml
>    loop:
It's deprecated type of package install. Please use passing a list to name through variable or directly:
```yaml
pip:
  name:
    - pyapi-gitlab
    - python-gitlab
```

2018-12-17 18:14 UTC, tgadiev commented on tasks/install.yml
> +  until: installed_packages is success
Nicely done!

2018-12-17 18:14 UTC, tgadiev commented on tasks/install.yml
>    with_first_found:
Why using `with_first_found` for single item?

2018-12-17 18:14 UTC, tgadiev commented on tasks/install.yml
> +  failed_when: gitlab_version | replace(' ', '') | length == 0
You have at least four subsequent tasks with the same conditional `when: not gitlab_file.stat.exists`.
How about making a block for them with common conditional?

2018-12-17 18:14 UTC, tgadiev commented on tasks/install.yml
>    file:
Comment for line 111:
why using command openssl call instead of `openssl_certificate` ansible module?

2018-12-17 18:14 UTC, tgadiev commented on tasks/selinux-gitlab.yml
>    loop:
Why do you need loop for single item?

2018-12-18 05:23 UTC, ViachaslauKabak commented on .travis.yml
> +  - pip install --upgrade ansible==2.5.* molecule==2.17 ansible-lint docker-py pyOpenSSL PyYAML pytest==3.7.4
fixed

2018-12-18 05:23 UTC, ViachaslauKabak commented on tasks/install.yml
>    loop:
fixed

2018-12-18 05:24 UTC, ViachaslauKabak commented on tasks/install.yml
> +  failed_when: gitlab_version | replace(' ', '') | length == 0
not in scope of this issue
please open issue

2018-12-18 05:24 UTC, ViachaslauKabak commented on tasks/install.yml
>    file:
not in scope of this issue
please open issue

2018-12-18 08:58 UTC, tgadiev approved these changes

2018-12-18 09:04 UTC, merged